# Adds ports to the db and access to the temporal UI for debugging purposes.
# Expected to be used like this:
# VERSION=dev docker-compose -f docker-compose.yaml -f docker-compose.datadog.yaml up
version: "3.7"
services:
  datadog:
    image: datadog/agent:7-rc
    container_name: airbyte-datadog
    environment:
      - DD_API_KEY
      - DD_ENV=${DD_ENV:-local}
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
      - DD_APM_ENABLED=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
  init:
    environment:
      - DATADOG_HOST=datadog
  bootloader:
    environment:
      - DATADOG_HOST=datadog
  worker:
    environment:
      - DATADOG_HOST=datadog
  server:
    environment:
      - DD_AGENT_HOST=airbyte-datadog
  airbyte-cron:
    environment:
      - DATADOG_HOST=datadog